services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: personal-podcast-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./src/storage:/var/www/html/storage
    networks:
      - podcast-network

  webserver:
    image: nginx:alpine
    container_name: podcast-feed-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - podcast-network
    depends_on:
      - app

networks:
  podcast-network:
    driver: bridge
